version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-network
    depends_on:
      - fairharvest-web

  # Fair Harvest Website
  fairharvest-web:
    build: .
    image: fairharvest:latest
    container_name: fairharvest-web-proxied
    restart: unless-stopped
    networks:
      - proxy-network
    environment:
      - NODE_ENV=${NODE_ENV:-development}

networks:
  proxy-network:
    name: proxy-network
    driver: bridge